import { jsPDF } from "jspdf";
import { ArgusSession } from "@/argus/session";

export const generateManuscriptPDF = (session: ArgusSession) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Header
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("ARGUS AUDIT REPORT", pageWidth / 2, y, { align: "center" });
    y += 15;

    doc.setFontSize(10);
    doc.setFont("courier", "normal");
    doc.text(`SESSION ID: ${session.id || "EPHEMERAL"}`, pageWidth / 2, y, { align: "center" });
    y += 10;
    doc.text(`DATE: ${new Date().toISOString()}`, pageWidth / 2, y, { align: "center" });
    y += 20;

    // Divider
    doc.line(20, y, pageWidth - 20, y);
    y += 15;

    // Content Warning
    doc.setFontSize(12);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(100);
    doc.text("This document constitutes a rigorous adversarial critique.", 20, y);
    y += 10;
    doc.text("All claims have been subjected to multi-agent simulation.", 20, y);
    doc.setTextColor(0);
    y += 20;

    // Claims Loop
    session.data.claims.forEach((claim, index) => {
        // Check for page break
        if (y > 250) {
            doc.addPage();
            y = 20;
        }

        // Claim Header
        doc.setFillColor(240, 240, 240);
        doc.rect(20, y - 5, pageWidth - 40, 15, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.text(`CLAIM ${index + 1}: ${claim.status || "PENDING"}`, 25, y + 2);
        y += 20;

        // Claim Text
        doc.setFont("times", "normal");
        doc.setFontSize(11);
        const splitClaim = doc.splitTextToSize(`"${claim.statement}"`, pageWidth - 40);
        doc.text(splitClaim, 20, y);
        y += (splitClaim.length * 7) + 10;

        // Governance Logs
        if (claim.governanceLog && claim.governanceLog.length > 0) {
            claim.governanceLog.forEach((log) => {
                if (y > 270) {
                    doc.addPage();
                    y = 20;
                }
                doc.setFont("courier", "bold");
                doc.setFontSize(9);
                doc.setTextColor(50);
                doc.text(`[${log.role}]`, 25, y);
                y += 5;

                doc.setFont("courier", "normal");
                const splitLog = doc.splitTextToSize(log.content, pageWidth - 50);
                doc.text(splitLog, 30, y);
                y += (splitLog.length * 5) + 8;
            });
            doc.setTextColor(0);
        }
        y += 10;
    });

    // Footer Disclaimer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Generated by ARGUS Governance Protocol. Ephemeral Data.", pageWidth / 2, 290, { align: "center" });
    }

    doc.save("argus_audit_manuscript.pdf");
};
